#!/bin/bash

# initalize environments and functions
source "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/env"

# Install dependencies WHEN NOT hot deploy OR vendor dir DOES NOT EXIST
if [[ ! -f "$OPENSHIFT_REPO_DIR/.openshift/markers/hot_deploy" ]] || [[ ! -d "$OPENSHIFT_REPO_DIR/vendor" ]]; then
  # Install dependencies
  unset GIT_DIR
  cd $OPENSHIFT_REPO_DIR
  php $OPENSHIFT_DATA_DIR/composer.phar install

  # Backup vendor dir
  if [ -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
    mkdir -p "$OPENSHIFT_DATA_DIR/vendor"
    rsync -ap --delete "$OPENSHIFT_REPO_DIR/vendor/" "$OPENSHIFT_DATA_DIR/vendor/"
  fi
fi
